version: "3.8"
services:
  redis:
    image: redis:13.3
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: my-password
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backnet 
  app:
    build: . 
    environment:
      STATIC_SERVE_PORT: 8090
      STATIC_ROOT_PATH: '/api/v1'
    command: poetry run static 
    networks:
      - backnet
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "123"
    networks:
      - backnet

    
networks:
  backnet:
