version: '3.8'

services:
  # web:
  #   build: ./app
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./app/:/usr/src/app/
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db
  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: hello_django
      KC_DB_PASSWORD: hello_django

      # KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 8080
      # KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # KC_HTTP_RELATIVE_PATH: /keycloak
      # PROXY_ADDRESS_FORWARDING: true
    command: start-dev
    ports: 
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:15
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/docker-postgresql-multiple-databases.sh:/docker-entrypoint-initdb.d/docker-postgresql-multiple-databases.sh
    environment:
      POSTGRES_USER: hello_django
      POSTGRES_PASSWORD: hello_django
      POSTGRES_MULTIPLE_DATABASES: keycloak, hello_django_dev
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./static/:/var/www/app/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data: