version: '3.8'

services:
  # web:
  #   build: ./app
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./app/:/usr/src/app/
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=hello_django
  #     - POSTGRES_PASSWORD=hello_django
  #     - POSTGRES_DB=hello_django_dev
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8080:80
    volumes:
      - ./static/:/var/www/app/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data: