version: "3.8"
services:
  app:
    build: . 
    environment:
      STATIC_SERVE_PORT: 8090
      STATIC_ROOT_PATH: '/api/v1'
    command: poetry run static 
    networks:
      - backnet

  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./web/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backnet

    
networks:
  backnet:
