version: "3.8"
services:
  app:
    build: . 
    environment:
      STATIC_SERVE_PORT: 8090
      STATIC_ROOT_PATH: '/api/v1'
    command: poetry run static 
    networks:
      - backnet

   minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022

    
networks:
  backnet:
